src/AppBundle/Entity/Person.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Person
 *
 * @ORM\Table(name="person")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks()
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
class Person
{

    const MARITAL_STATUS_SINGLE = 1;
    const MARITAL_STATUS_MARRIED = 2;
    const MARITAL_STATUS_DIVORCED = 3;
    const MARITAL_STATUS_WIDOWED = 4;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="gender", type="string", length=1, nullable=true)
     */
    private $gender;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @var string
     *
     * @ORM\Column(name="business_name", type="string", length=255, nullable=true)
     */
    private $businessName;

    /**
     * @var integer
     *
     * @ORM\Column(name="marital_status_id", type="integer", nullable=true)
     */
    private $maritalStatusId;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="telephone", type="string", length=32, nullable=true)
     */
    private $telephone;

    /**
     * @var string
     *
     * @ORM\Column(name="mobile", type="string", length=32, nullable=true)
     */
    private $mobile;

    /**
     * @var string
     *
     * @ORM\Column(name="telephone_work", type="string", length=32, nullable=true)
     */
    private $telephoneWork;

    /**
     * @var string
     *
     * @ORM\Column(name="fax", type="string", length=32, nullable=true)
     */
    private $fax;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dob", type="date", nullable=true)
     */
    private $dob;

    /**
     * @var string
     *
     * @ORM\Column(name="nric_passport", type="string", length=255, nullable=true)
     */
    private $nricPassport;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="deleted_at", type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="modified", type="datetime", nullable=true)
     */
    private $modified;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created", type="datetime", nullable=true)
     */
    private $created;



    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Person
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return Person
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string 
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     * @return Person
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string 
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Person
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set telephone
     *
     * @param string $telephone
     * @return Person
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * Get telephone
     *
     * @return string 
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * Set mobile
     *
     * @param string $mobile
     * @return Person
     */
    public function setMobile($mobile)
    {
        $this->mobile = $mobile;

        return $this;
    }

    /**
     * Get mobile
     *
     * @return string 
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Set fax
     *
     * @param string $fax
     * @return Person
     */
    public function setFax($fax)
    {
        $this->fax = $fax;

        return $this;
    }

    /**
     * Get fax
     *
     * @return string 
     */
    public function getFax()
    {
        return $this->fax;
    }

    /**
     * Set deleted
     *
     * @param \DateTime $deletedAt
     * @return DocumentType
     */
    public function setDeletedAt($deletedAt)
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    /**
     * Get deleted
     *
     * @return \DateTime
     */
    public function getDeletedAt()
    {
        return $this->deletedAt;
    }

    /**
     * Set modified
     *
     * @param \DateTime $modified
     * @return Person
     */
    public function setModified($modified)
    {
        $this->modified = $modified;

        return $this;
    }

    /**
     * Get modified
     *
     * @return \DateTime 
     */
    public function getModified()
    {
        return $this->modified;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Person
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Get the full name of the person as a string
     * @return string
     */
    public function getFullName() {
        return ucwords(trim($this->getTitle().' '.$this->getFirstName().' '.$this->getLastName()));
    }

    /**
     * Set dob
     *
     * @param \DateTime $dob
     *
     * @return Person
     */
    public function setDob($dob)
    {
        $this->dob = $dob;

        return $this;
    }

    /**
     * Get dob
     *
     * @return \DateTime
     */
    public function getDob()
    {
        return $this->dob;
    }

    /**
     * Set businessName
     *
     * @param string $businessName
     *
     * @return Person
     */
    public function setBusinessName($businessName)
    {
        $this->businessName = $businessName;

        return $this;
    }

    /**
     * Get businessName
     *
     * @return string
     */
    public function getBusinessName()
    {
        return $this->businessName;
    }
    
    public static function getMaritalStatusOptions()
    {
        return [
            self::MARITAL_STATUS_SINGLE => 'Single',
            self::MARITAL_STATUS_MARRIED => 'Married',
            self::MARITAL_STATUS_DIVORCED => 'Divorced',
            self::MARITAL_STATUS_WIDOWED => 'Widowed',
        ];
    }

    public function getMaritalStatusName() {
        if ($this->getMaritalStatusId()) {
            return self::getMaritalStatusOptions()[$this->getMaritalStatusId()];
        }
    }

    /**
     * Set gender
     *
     * @param string $gender
     *
     * @return Person
     */
    public function setGender($gender)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Get gender
     *
     * @return string
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Set maritalStatusId
     *
     * @param integer $maritalStatusId
     *
     * @return Person
     */
    public function setMaritalStatusId($maritalStatusId)
    {
        $this->maritalStatusId = $maritalStatusId;

        return $this;
    }

    /**
     * Get maritalStatusId
     *
     * @return integer
     */
    public function getMaritalStatusId()
    {
        return $this->maritalStatusId;
    }

    /**
     * Set telephoneWork
     *
     * @param string $telephoneWork
     *
     * @return Person
     */
    public function setTelephoneWork($telephoneWork)
    {
        $this->telephoneWork = $telephoneWork;

        return $this;
    }

    /**
     * Get telephoneWork
     *
     * @return string
     */
    public function getTelephoneWork()
    {
        return $this->telephoneWork;
    }

    /**
     * Set nricPassport
     *
     * @param string $nricPassport
     *
     * @return Person
     */
    public function setNricPassport($nricPassport)
    {
        $this->nricPassport = $nricPassport;

        return $this;
    }

    /**
     * Get nricPassport
     *
     * @return string
     */
    public function getNricPassport()
    {
        return $this->nricPassport;
    }

    /**
     * Get person name initials
     * @return string
     */
    public function getInitials() {
        $initials = '';
        if ($this->getFirstName()) {
            $initials .=$this->getFirstName()[0];
        }
        if ($this->getLastName()) {
            $initials .=$this->getLastName()[0];
        }
        return $initials;
    }
}

src/AppBundle/Form/Type/Client.php
<?php
/**
 * Client.php
 *
 * @author Gul
 */

namespace AppBundle\Form\Type;

use AppBundle\Form\Type\FinancialAdviserRegistration;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class Client extends AbstractType
{

   public function buildForm(FormBuilderInterface $builder, array $options)
   {
      $builder->add('person', Person::class);
      
      $builder->add('address', Address::class);
   }

   public function configureOptions(OptionsResolver $resolver)
   {
      $resolver->setDefaults(array(
         'data_class' => 'AppBundle\Entity\Client',
         'csrf_protection' => true,
      ));

   }


   public function getName()
   {
      return 'client';
   }

}

src/AppBundle/Resources/views/Client/widget/client-event-types-form.html.twig
{{ form_start(client_event_types_form, {attr: {id: 'client-event-types-form', class: 'form live-form'}}) }}

    {{ form_errors(client_event_types_form) }}
    {{ form_widget(client_event_types_form._token) }}

    {% for clientEventType in client_event_types_form.clientEventTypes %}
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label for="client-event-type-{{ clientEventType.vars.value.id }}">Pipeline Event {{ loop.index }}</label>
                {{ form_widget(clientEventType.name, {attr: {class: 'form-control'}}) }}
            </div>
        </div>
    {% endfor %}
    {% for i in client_event_types_form.clientEventTypes|length..9 %}
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label for="client-event-type-i-{{ i }}">Pipeline Event {{ i+1 }}</label>
                <input type="text" value="" name="client_event_types[clientEventTypes][{{ i }}][name]" class="form-control" />
            </div>
        </div>
    {% endfor %}

    <div class="row text-right ">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success m-r-15">Save</button>
    </div>

{{ form_end(client_event_types_form, {render_rest: false}) }}

src/AppBundle/Resources/views/Client/widget/client-event-types-modal.html.twig
<!-- MODAL STICK UP  -->
<div class="modal fade stick-up" id="client-event-types-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header clearfix text-left">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
                </button>
                <h5><span class="semi-bold">Pipeline Event</span></h5>
                <p>The standard list of Pipelines Events you can choose from are: <br/><i>First Contact, Appointment Made, Appointment Attended, Appointment Cancelled, Appointment Deferred, Offer Made, Counter Offer Made, Follow-Up, Offer Accepted, Offer Negotiated, Offer Declined, Offer Reviewed, Offer Complete</i><br/>
                    <br/>You can add up to 10 more.
                </p>
            </div>
            <div class="modal-body">

                {{ include('AppBundle:Client/widget:client-event-types-form.html.twig') }}

            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- END MODAL STICK UP  -->

src/AppBundle/Resources/views/Client/widget/wpm-tab-cashflow.html.twig
{# @var client \AppBundle\Entity\Client #}
{# @var clientWPM \AppBundle\Entity\ClientWPM #}

<div class="tab-pane slide-left active" id="cashflow">
    <div class="panel panel-transparent">
        <div class="panel-heading">
            <div class="panel-title">WPM - Cashflow</div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-9 col-md-7">
                    <h3>{{ client.person.fullName }}</h3>
                    <br/>

                    {{ form_start(form, {attr: {id: 'cashflow-form', class: 'live-form', 'novalidate': 'novalidate'}}) }}

                        {{ form_errors(form) }}
                        {{ form_widget(form._token) }}

                        <h3>Active Income</h3>

                        <div class="form-group-attached">
                            <div class="row">
                                <label class="col-sm-3 control-label">Salary</label>
                                <div class="col-sm-3">{{ form_row(form.salary) }}</div>
                                <div class="col-sm-3">{{ form_row(form.salaryMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.salaryDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Allowances</label>
                                <div class="col-sm-3">{{ form_row(form.allowances) }}</div>
                                <div class="col-sm-3">{{ form_row(form.allowancesMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.allowancesDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Commissions</label>
                                <div class="col-sm-3">{{ form_row(form.commissions) }}</div>
                                <div class="col-sm-3">{{ form_row(form.commissionsMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.commissionsDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Bonuses</label>
                                <div class="col-sm-3">{{ form_row(form.bonuses) }}</div>
                                <div class="col-sm-3">{{ form_row(form.bonusesMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.bonusesDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Other</label>
                                <div class="col-sm-3">{{ form_row(form.cashflowActiveOthers) }}</div>
                            </div>
                        </div>

                        <h3>Passive Income</h3>

                        <div class="form-group-attached">
                            <div class="row">
                                <label class="col-sm-3 control-label">Dividends</label>
                                <div class="col-sm-3">{{ form_row(form.dividends) }}</div>
                                <div class="col-sm-3">{{ form_row(form.dividendsMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.dividendsDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Coupons</label>
                                <div class="col-sm-3">{{ form_row(form.coupons) }}</div>
                                <div class="col-sm-3">{{ form_row(form.couponsMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.couponsDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Rentals</label>
                                <div class="col-sm-3">{{ form_row(form.rentals) }}</div>
                                <div class="col-sm-3">{{ form_row(form.rentalsMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.rentalsDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Other</label>
                                <div class="col-sm-3">{{ form_row(form.cashflowPassiveOthers) }}</div>
                            </div>
                        </div>

                        <h3>Fixed Expenses</h3>

                        <div class="form-group-attached">
                            <div class="row">
                                <label class="col-sm-3 control-label">Home</label>
                                <div class="col-sm-3">{{ form_row(form.home) }}</div>
                                <div class="col-sm-3">{{ form_row(form.homeMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.homeDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Transport</label>
                                <div class="col-sm-3">{{ form_row(form.transport) }}</div>
                                <div class="col-sm-3">{{ form_row(form.transportMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.transportDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Personal</label>
                                <div class="col-sm-3">{{ form_row(form.personal) }}</div>
                                <div class="col-sm-3">{{ form_row(form.personalMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.personalDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Food/Clothing</label>
                                <div class="col-sm-3">{{ form_row(form.food) }}</div>
                                <div class="col-sm-3">{{ form_row(form.foodMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.foodDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Medical/Dental</label>
                                <div class="col-sm-3">{{ form_row(form.medical) }}</div>
                                <div class="col-sm-3">{{ form_row(form.medicalMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.medicalDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Children</label>
                                <div class="col-sm-3">{{ form_row(form.children) }}</div>
                                <div class="col-sm-3">{{ form_row(form.childrenMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.childrenDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Loans</label>
                                <div class="col-sm-3">{{ form_row(form.loans) }}</div>
                                <div class="col-sm-3">{{ form_row(form.loansMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.loansDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Other</label>
                                <div class="col-sm-3">{{ form_row(form.cashflowFixedOthers) }}</div>
                            </div>
                        </div>

                        <h3>Variable Expenses</h3>

                        <div class="form-group-attached">
                            <div class="row">
                                <label class="col-sm-3 control-label">Recreation</label>
                                <div class="col-sm-3">{{ form_row(form.recreation) }}</div>
                                <div class="col-sm-3">{{ form_row(form.recreationMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.recreationDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Miscellaneous</label>
                                <div class="col-sm-3">{{ form_row(form.miscellaneous) }}</div>
                                <div class="col-sm-3">{{ form_row(form.miscellaneousMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.miscellaneousDate) }}</div>
                            </div>

                        </div>

                        <h3>Others</h3>

                        <div class="form-group-attached">
                            <div class="row">
                                <label class="col-sm-3 control-label">Insurances</label>
                                <div class="col-sm-3">{{ form_row(form.insurances) }}</div>
                                <div class="col-sm-3">{{ form_row(form.insurancesMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.insurancesDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Savings/Investments</label>
                                <div class="col-sm-3">{{ form_row(form.savings) }}</div>
                                <div class="col-sm-3">{{ form_row(form.savingsMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.savingsDate) }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 control-label">Gifts/Contributions</label>
                                <div class="col-sm-3">{{ form_row(form.gifts) }}</div>
                                <div class="col-sm-3">{{ form_row(form.giftsMode) }}</div>
                                <div class="col-sm-3">{{ form_row(form.giftsDate) }}</div>
                            </div>

                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">&nbsp;</label>
                            <div class="col-sm-9">
                                <button class="btn btn-primary btn-cons m-t-10" type="submit">Update</button>
                            </div>
                        </div>



                    {{ form_end(form, {render_rest: false}) }}

                </div>
            </div>
        </div>
    </div>
</div>

src/AppBundle/Resources/views/Client/widget/wpm-tab-estate.html.twig
{# @var client \AppBundle\Entity\Client #}
{# @var clientWPM \AppBundle\Entity\\AppBundle\Entity\ClientWPM #}

<div class="tab-pane slide-left" id="estate">
    <div class="panel panel-transparent">
        <div class="panel-heading">
            <div class="panel-title">WPM - Estate Planning</div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-9 col-md-7">
                    <h3>{{ client.person.fullName }}</h3>
                    <br/>

                    {{ form_start(form, {attr: {id: 'estate-form', class: 'live-form', 'novalidate': 'novalidate'}}) }}

                        {{ form_errors(form) }}
                        {{ form_widget(form._token) }}

                        <div class="panel-group" id="estates" >

                            {% for estateForm in form.clientWPMEstates %} {# @var estate \AppBundle\Entity\ClientWPMEstate #}
                                {{ include('AppBundle:Client/widget:wpm-tab-estate-form.html.twig', {estateForm: estateForm, client: client, index: loop.index}) }}
                            {% endfor %}


                        </div>
                        <div class="row">
                            <button id="add-estate" type="button" class="btn btn-success" data-client-id="{{ client.id }}"><i class="fa fa-plus"></i> Add Estate</button>
                            <button id="save-estates" class="btn btn-primary btn-cons m-t-10 pull-right" type="submit" style="display: {{ form.clientWPMEstates|length > 0 ? 'block' : 'none' }}">Save changes</button>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">&nbsp;</label>
                            <div class="col-sm-9">

                            </div>
                        </div>



                    {{ form_end(form, {render_rest: false}) }}

                </div>
            </div>
        </div>
    </div>
</div>

src/AppBundle/Resources/views/Client/widget/wpm-tab-insurance.html.twig
{# @var client \AppBundle\Entity\Client #}
{# @var clientWPM \AppBundle\Entity\\AppBundle\Entity\ClientWPM #}

<div class="tab-pane slide-left" id="insurance">
    <div class="panel panel-transparent">
        <div class="panel-heading">
            <div class="panel-title">WPM - Insurance Planning</div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-9 col-md-7">
                    <h3>{{ client.person.fullName }}</h3>
                    <br/>

                    {{ form_start(form, {attr: {id: 'insurance-form', class: 'live-form', 'novalidate': 'novalidate'}}) }}

                        {{ form_errors(form) }}
                        {{ form_widget(form._token) }}

                        <div class="panel-group" id="insurance-policies" >

                            {% for insurancePolicyForm in form.clientWPMInsurancePolicies %} {# @var insurancePolicy \AppBundle\Entity\ClientWPMInsurancePolicy #}
                                {{ include('AppBundle:Client/widget:wpm-tab-insurance-policy-form.html.twig', {insurancePolicyForm: insurancePolicyForm, client: client, index: loop.index}) }}
                            {% endfor %}


                        </div>
                        <div class="row">
                            <button id="add-insurance-policy" type="button" class="btn btn-success" data-client-id="{{ client.id }}"><i class="fa fa-plus"></i> Add Insurance Policy</button>
                            <button id="save-insurance-policies" class="btn btn-primary btn-cons m-t-10 pull-right" type="submit" style="display: {{ form.clientWPMInsurancePolicies|length > 0 ? 'block' : 'none' }}">Save changes</button>
                        </div>





                    {{ form_end(form, {render_rest: false}) }}

                </div>
            </div>
        </div>
    </div>
</div>

src/AppBundle/Resources/views/Client/widget/wpm-tab-investment.html.twig
{# @var client \AppBundle\Entity\Client #}
{# @var clientWPM \AppBundle\Entity\\AppBundle\Entity\ClientWPM #}

<div class="tab-pane slide-left" id="investment">
    <div class="panel panel-transparent">
        <div class="panel-heading">
            <div class="panel-title">WPM - Investment Planning</div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-9 col-md-7">
                    <h3>{{ client.person.fullName }}</h3>
                    <br/>

                    {{ form_start(form, {attr: {id: 'investment-form', class: 'live-form', 'novalidate': 'novalidate'}}) }}

                        {{ form_errors(form) }}
                        {{ form_widget(form._token) }}

                        <div class="panel-group" id="investments" >

                            {% for investmentForm in form.clientWPMInvestments %} {# @var investment \AppBundle\Entity\ClientWPMInvestment #}
                                {{ include('AppBundle:Client/widget:wpm-tab-investment-form.html.twig', {investmentForm: investmentForm, client: client, index: loop.index}) }}
                            {% endfor %}


                        </div>
                        <div class="row">
                            <button id="add-investment" type="button" class="btn btn-success" data-client-id="{{ client.id }}"><i class="fa fa-plus"></i> Add Investment</button>
                            <button id="save-investments" class="btn btn-primary btn-cons m-t-10 pull-right" type="submit" style="display: {{ form.clientWPMInvestments|length > 0 ? 'block' : 'none' }}">Save changes</button>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">&nbsp;</label>
                            <div class="col-sm-9">

                            </div>
                        </div>



                    {{ form_end(form, {render_rest: false}) }}

                </div>
            </div>
        </div>
    </div>
</div>